name: CI

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v2.0.0
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            
      - name: Make .env
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_USER_ID: ${{ secrets.USER_ID }}
          envkey_USER_PWD: ${{ secrets.USER_PWD }}
          envkey_TRAINEE_NAME: ${{ secrets.TRAINEE_NAME }}
          envkey_TRAINEE_BIRTH: ${{ secrets.TRAINEE_BIRTH }}
          envkey_ENTER_DATE: ${{ secrets.ENTER_DATE }}
          envkey_CLASS_NAME: ${{ secrets.CLASS_NAME }}
          envkey_GROUP_NAME: ${{ secrets.GROUP_NAME }}
          envkey_UNIT_NAME: ${{ secrets.UNIT_NAME }}
          envkey_TEST: ${{ secrets.TEST }}
          file_name: .env

      - name: Npm install
        run: |
          npm i
          
      - name: Run Cron
        run: |
          npm run start
